const RouteConstant = {
    MY_PROFILE: "my-profile",
    EDIT_PROFILE: "edit-profile",
    LANDING_PAGE: "/",
    ENTERPRISE_SIGNUP: "/signup/enterprise",
    FREELANCER_SIGNUP: "/signup/freelancer",
    ENTERPRISE_LOGIN: "/login/enterprise",
    FREELANCER_LOGIN: "/login/freelancer",
    WELCOME: "/welcome",
    ONBOARDING: "/onboarding",
    ONBOARDING_SUCCESS: "onboarding/success",
    AGENCY: "onboarding/agency",
    AGENCY_DETAILS: "onboarding/agency-details",
    HOME: "/home",
    NON_MEMBER: "non-member",
    EXPLORE_GIGS: "explore-gigs",
    GIG_TEMPLATE: "gig-template",
    CREATE_GIG: "create-gig",
    REVIEW_GIG_DETAILS: "review-gig-details",
    MILESTONE_DETAILS: "milestone-details",
    GIG_MILESTONE: "gig-milestone",
    EXPLORE_TALENT: "explore-talent",
    FREELANCER_PROFILE: "freelancer-profile",
    BIDS_AND_OFFERS: "bids-and-offers",
    BIDS_AND_OFFERS_DETAILS: "bids-and-offers-details",
    GIG_STATUS: "gig-status",
    GIG_DETAILS: "gig-details",
    MILESTONE_TIMELINE: "milestone-timeline",
    ACCOUNT_SETTINGS: "account-settings",
    REVIEWS_AND_RATINGS: "reviews-and-ratings",
    SEARCH_RESULTS: "search-results",
    INVOICES: "invoices",
    DASHBOARD: "dashboard",
    PAYMENTS: "payments",
};

export default RouteConstant;
